<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="NOODP">
    <meta name="description" content="It's going to get a little crazy on this blog! I am a new father, loving husband, and stay at home 'fommy.' Join me on my journey as I discuss hot-button topics and re-tell the mostly humourous side of being a family-mant.">
    <meta name="keywords" content="giggles, shit, giggles n shit, blog, parent, father, fommy, stay at home, funny, humour, dad, newborn, baby, nursery, web development, tech">
    <meta name="author" content="Evan Marshall">
    <link rel="icon" href="#">

    <title>Giggles N Shit Blog</title>
    
    <!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
	<script type="application/ld+json">
		[ {
		  "@context" : "http://schema.org",
		  "@type" : "Product",
		  "name" : "Giggles N Shit Blog",
		  "url" : "http://www.gigglesnshit.com/"
		}, {
		  "@context" : "http://schema.org",
		  "@type" : "Product",
		  "name" : "Giggles N Shit",
		  "image" : [ "http://www.google.com/img/portfolio/hospital.jpg", "http://www.google.com/img/portfolio/family.jpg", "http://www.google.com/img/portfolio/poo-chair.jpg", "http://www.google.com/img/portfolio/daddys-girl.jpg", "http://www.google.com/img/portfolio/football.jpg", "http://www.google.com/img/portfolio/playpin.jpg" ],
		  "description" : "It&#39;s going to get a little crazy on this blog! I am a new father, loving husband, and stay at home &#39;fommy.&#39; Join me on my journey as I discuss hot-button topics and re-tell the mostly humourous side of being a family-man.",
		  "url" : "http://www.gigglesnshit.com/"
		} ]
	</script>

<!-- MINIFIED BOOTSTRAP CSS ====================================================================================================================================== -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet" integrity="sha256-7s5uDGW3AHqw6xtJmNNtr+OBRJUlgkNJEo78P4b0yRw= sha512-nNo+yCHEyn0smMxSswnf/OnX6/KwJuZTlNZBjauKhTK0c+zT+q5JOCx0UFhXQ6rJR9jg6Es8gPuD2uZcYDLqSw==" crossorigin="anonymous">

<!-- CUSTOM FONTS ================================================================================================================================================ -->
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic" rel="stylesheet" type="text/css">
    
<!-- FONT-AWESOME ================================================================================================================================================ -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha256-3dkvEK0WLHRJ7/Csr0BZjAWxERc5WH7bdeUya2aXxdU= sha512-+L4yy6FRcDGbXJ9mPG8MT/3UCDzwR9gPeyFNMCtInsol++5m3bk2bXWKdZjvybmohrAsn3Ua5x8gfLnbE1YkOg==" crossorigin="anonymous">

<!-- FAVICONS ==================================================================================================================================================== -->    
 	<link rel="apple-touch-icon" sizes="57x57" href="/img/favicon/apple-touch-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="/img/favicon/apple-touch-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="/img/favicon/apple-touch-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="/img/favicon/apple-touch-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="/img/favicon/apple-touch-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="/img/favicon/apple-touch-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="/img/favicon/apple-touch-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/img/favicon/apple-touch-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="/img/favicon/apple-touch-icon-180x180.png">
    <link rel="icon" type="image/png" href="/img/favicon/favicon-32x32.png" sizes="32x32">
    <link rel="icon" type="image/png" href="/img/favicon/android-chrome-192x192.png" sizes="192x192">
    <link rel="icon" type="image/png" href="/img/favicon/favicon-96x96.png" sizes="96x96">
    <link rel="icon" type="image/png" href="/img/favicon/favicon-16x16.png" sizes="16x16">
    <link rel="manifest" href="/img/favicon/manifest.json">
    <link rel="mask-icon" href="/img/favicon/safari-pinned-tab.svg" color="#5763ac">
    <link rel="shortcut icon" href="/img/favicon/favicon.ico">
    <meta name="apple-mobile-web-app-title" content="GigglesNShit">
    <meta name="application-name" content="GigglesNShit">
    <meta name="msapplication-TileColor" content="#5763ac">
    <meta name="msapplication-TileImage" content="/img/favicon/mstile-144x144.png">
    <meta name="msapplication-config" content="/img/favicon/browserconfig.xml">
    <meta name="theme-color" content="#5763ac">

<!-- PLUGIN CSS ================================================================================================================================================== -->
    <link rel="stylesheet" href="css/animate.min.css" type="text/css">

<!-- CUSTOM CSS ================================================================================================================================================== -->
    <link rel="stylesheet" href="css/creative.css" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body id="page-top">

    <nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand page-scroll" href="#page-top">Giggles N Shit Blog</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a class="page-scroll" href="#about">Introduction</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#services">Sales &amp; Service</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#portfolio">Recent Posts</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#contact">Contact</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>

    <header>
        <div class="header-content">
            <div class="header-content-inner">
            	<?php
					include("php/signup.php");
				?>
                <h1>Giggles N Shit</h1>
                <hr>
                <p>It's going to get a little crazy on this blog! I am a new father, loving husband, and stay at home 'fommy.' Join me on my journey as I discuss hot-button topics and re-tell the mostly humourous side of being a family-man.</p>
                <a href="#about" class="btn btn-primary btn-xl page-scroll">Introduction</a>
            </div>
        </div>
    </header>

    <section class="bg-primary" id="about">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 text-center">
                    <h2 class="section-heading">Why the hell do I want to write a blog??</h2>
                    <hr class="light">
                    <p class="text-faded">I have been entertaining the thought of writing a blog now for some time. I thought to myself: "Evan, blogs are a good form of therapy and they will also provide you with a good excuse to practice your web development." "Evan, you're so smart!"</p>
                    
                    <p class="text-faded">I stand here today with a Huggies wet wipe in one hand and broken dreams in the other hand. I am wiping the cream coloured, sour milk scented crap off of my 4 month old daughter's butt ("how the F did it end up on her armpit and belly button?") and I have an idea. Firstly, I've always felt uneasy when I slap some zinc cream on my finger and wipe it on her anus as she looks up to me with a loving smile on her face. Secondly, as I converse with a fellow co-worker about a bullying issue her son is dealing with at school, I realize I have a great theme for a blog!! Side note: I will most likely talk about the bully conversation in a near-future blog post. The details will introduce to you how I will handle these situatons with my own daughter.</p>
                    
                    <p class="text-faded">What about: my life's re-telling of the day to day situations I find myself in with a little touch of humour and ridiculousness? These situations will be in regards to being a father, husband and friend. I know what you're thinking. "Evan, There's a million of those types of blogs out there." Maybe you're not thinking that and you are thinking I'm a genius (this is the more likely scenario). The difference between all of those other blogs and mine is that I have been told that I have an incredible ability to find humour in some of the most disgusting, upsetting, depressing, frustrating, exciting, scary, happy, (too many emotional adjectives?), real life situations. Also, I can't stand the norm. I hate how children are sheltered from dealing with the many nuances of growing up. I hate how children parent the parents now. I hate the anti-bullying campaigns out there (see future posts). It's not that I don't think something has to be done about it, it's just that I think we are going about it all wrong, as I feel with many hot topics. Oh, and there will be profanity. I loooove profanity. Not as much as my wife though... she swears like a sailor and not some pansy, white cap wearing sailor. She is one of those life-long, wrinkled-up, salty tasting, anchor and ship tattooed sailors from Newfoundland.</p>
                    
                    <p class="text-faded">I'm blunt, extremely sarcastic, ridiculous, and I have very strong opinions on how you should raise a child, even though I've only been a parent for 4 months (I have strong opinions on a lot of things... I'm an ass...). I encourage open debates, as long as you can handle my rebuttals. I am also not afraid to test my theories over the next 18 years as my sweet, beautiful, heart-pinching baby girl grows up in some of the most challenging times. I'm sure I'll even be wrong sometimes, however unlikely that might be.</p>
                    
                    <p class="text-faded">I hope you will enjoy my journey of parenthood and husband-hood &copy;. I know I'm looking forward to it!!</p>
                    <a href="#" class="btn btn-default btn-xl">About the Author</a>
                </div>
            </div>
        </div>
    </section>

    <section id="services">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2 class="section-heading">Is This Blog for You?</h2>
                    <h3>Here are some of the things you should expect</h3>
                    <hr class="primary">
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-6 text-center">
                    <div class="service-box">
                        <i class="fa fa-4x fa-commenting wow bounceIn text-primary"></i>
                        <h3>Active Participation from the Author</h3>
                        <p class="text-muted">I will have a comment section on each blog post. I encourage you to comment on any topic I cover and I will do my best to partake in the discussion as well. I will have links to my social networking accounts and I fully encourage you to post pictures of your little ones, tell your funny stories, and meet other parents in the struggle.</p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 text-center">
                    <div class="service-box">
                        <i class="fa fa-4x fa-pencil wow bounceIn text-primary" data-wow-delay=".1s"></i>
                        <h3>I Have Other Hobbies</h3>
                        <p class="text-muted">I have been sketching my entire life and I even have some future posts in which you can see some of my recent work. I am a <strong>HUGE</strong> tech geek both personally and professionally. I also have been dabbing in the wonderful world of web development over the past year or so (I created this webpage!). Sooooo... expect some free gifts, if you are an active member of my blog, and check out my <a href="#">sales &amp; service</a> section. In this section you will find offers on webpage creations at a fabulous price, technological woes resolved by yours truly, as well as sketches up for sale!</p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 text-center">
                    <div class="service-box">
                        <i class="fa fa-4x fa-gift wow bounceIn text-primary" data-wow-delay=".2s"></i>
                        <h3>Sign Up!</h3>
                        <p class="text-muted">I will be posting blogs quite frequently so make sure you <a href="php/signup-form.php">sign up</a> to my blog community so you don't miss any new blog posts, important communications, as well as special gifts just for you! Do not worry, I will never spam you, spammers are douches! Also keep in mind that my blog posts will be very dynamic. They will contain pictures and videos... I find plain text makes my head spin after a while so I want to spruce it up for ya!</p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 text-center">
                    <div class="service-box">
                        <i class="fa fa-4x fa-hand-peace-o wow bounceIn text-primary" data-wow-delay=".3s"></i>
                        <h3>All in Good Fun</h3>
                        <p class="text-muted">I know I said I am opinionated, I will be discussing hot-button topics, and I am open to debate. I fully expect that this means some people will get offended and pretty heated in the comment sections. Please keep in mind that the intentions of the blog are to provide a light-hearted view of the world we live in and is not intended to offend or say that any one else's opinions are wrong. There is enough bull we deal with out there on a day-to-day basis and I hope my blog can illicit a good chuckle out of you even if for a brief moment.</p>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section class="no-padding" id="portfolio">
        <div class="container-fluid">
            <div class="row no-gutter">
                <div class="col-lg-4 col-sm-6">
                    <a href="pages/blog-1.php?id=1" class="portfolio-box">
                        <img src="img/portfolio/announcement.jpg" class="img-responsive" alt="">
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">
                                    "Shit, I'm Pregnant..."
                                </div>
                                <div class="project-name">
                                    March 20th, 2016
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-4 col-sm-6">
                    <a href="pages/blog-2.php?id=2" class="portfolio-box">
                        <img src="img/portfolio/watermelon.JPG" class="img-responsive" alt="">
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">
                                 	"The Watermelon Incident..."
                                </div>
                                <div class="project-name">
                                 	March 28th, 2016
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-4 col-sm-6">
                    <a href="#" class="portfolio-box">
                        <img src="img/portfolio/poo-chair.jpg" class="img-responsive" alt="">
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">
                                    POST 3 - DATE
                                </div>
                                <div class="project-name">
                                    Coming Soon!
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-4 col-sm-6">
                    <a href="#" class="portfolio-box">
                        <img src="img/portfolio/daddys-girl.jpg" class="img-responsive" alt="">
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">
                                    POST 4 - DATE
                                </div>
                                <div class="project-name">
                                    Coming Soon!
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-4 col-sm-6">
                    <a href="#" class="portfolio-box">
                        <img src="img/portfolio/football.jpg" class="img-responsive" alt="">
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">
                                    POST 5 - DATE
                                </div>
                                <div class="project-name">
                                    Coming Soon!
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-4 col-sm-6">
                    <a href="#" class="portfolio-box">
                        <img src="img/portfolio/playpin.jpg" class="img-responsive" alt="">
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">
                                    POST 6 - DATE
                                </div>
                                <div class="project-name">
                                    Coming Soon!
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
        </div>
    </section>
    
    <aside class="bg-dark">
        <div class="container text-center">
            <div class="call-to-action">
                <h2>The First 30 Members Who Sign Up to the Blog Will Receive a <strong>FREE</strong> iPhone 6/6s Tempered Glass Screen Protector!</h2>
                
                <!-- Button trigger modal -->
				<button type="button" class="btn btn-default btn-xl wow tada" data-toggle="modal" data-target="#myModal">
  					Join Here!
				</button>

				<!-- Modal -->
				<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  					<div class="modal-dialog" role="document">
    					<div class="modal-content">
      						<div class="modal-header">
        						<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        						<h4 style="color:#5763AC;" class="modal-title" id="myModalLabel">Please Fill Out All Boxes to Register</h4>
      						</div><!-- ./header -->

							<?php
                                include("php/signup-form.php");
                            ?>
                            
                                					</div><!-- ./content -->
  					</div><!-- ./dialog -->
				</div><!-- ./modal -->
            </div>
        </div>
    </aside>

    <section id="contact">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 text-center">
                 	<h2 class="section-heading">Drop me a Line</h2>
                  	<hr class="primary">
                  	<p>Feel free to contact me anytime, anyday via my personal email or social media accounts.</p>
                    <div class="col-lg-12 text-center">
                        <i class="fa fa-envelope-o fa-3x wow bounceIn" data-wow-delay=".1s"></i>
                        <p><a href="mailto:evanmarshall1986@gmail.com">EMAIL ME!</a></p>
                    </div>
                    <div class="col-lg-3 text-center">
                        <a href="https://www.facebook.com/evan.marshall.3762"><i class="fa fa-facebook fa-3x wow bounceIn" data-wow-delay=".1s"></i></a>
                    </div>
                    <div class="col-lg-3 text-center">
                        <a href="https://www.instagram.com/instagingagram/"><i class="fa fa-instagram fa-3x wow bounceIn" data-wow-delay=".1s"></i></a>
                    </div>
                    <div class="col-lg-3 text-center">
                        <a href="https://www.etsy.com/ca/shop/BabyIslay?ref=shopinfo_shophome_leftnav"><i class="fa fa-shopping-cart fa-3x wow bounceIn" data-wow-delay=".1s"></i></a>
                    </div>
                    <div class="col-lg-3 text-center">
                        <a href="https://www.pinterest.com/BabyIslay/"><i class="fa fa-pinterest fa-3x wow bounceIn" data-wow-delay=".1s"></i></a>
                    </div>
        		</div>
     		</div>
     	</div>
 	</section>
            
    <section id="admin" class="bg-dark">
        <div class="container">
            <div class="row">
                <div class="col-lg-4">
                    <p>To login click <a href="#">HERE</a></p><br>
                    <p>To update profile click <a href="#">HERE</a></p><br>
                    <p>To update password click <a href="php/password.php">HERE</a></p><br>
             	</div>
            
            	<div class="text-center col-lg-4">
            		<!-- Start of StatCounter Code for Dreamweaver -->
					<script type="text/javascript">
						var sc_project=10886934; 
						var sc_invisible=0; 
						var sc_security="c23d5ac3"; 
						var scJsHost = (("https:" == document.location.protocol) ?
						"https://secure." : "http://www.");
						document.write("<sc"+"ript type='text/javascript' src='" +scJsHost+ "statcounter.com/counter/counter.js'></"+"script>");
                	</script>
                	<noscript>
                		<div class="statcounter">
                    		<a title="shopify stats"href="http://statcounter.com/shopify/" target="_blank">
                        		<img class="statcounter"src="http://c.statcounter.com/10886934/0/c23d5ac3/0/" alt="shopify stats">
                     		</a>
                		</div>
             		</noscript>
                	<!-- End of StatCounter Code for Dreamweaver -->
    				<a href="http://statcounter.com/p10886934/?guest=1">View My Stats</a>
            	</div>
                <div class="text-center col-lg-4">
                    <p>&copy; <a href="http://www.gigglesnshit.com">Giggles N Shit Blog</a> - 2016</p>
        		</div>
         	</div>
    	</div>
    </section>

<!-- MINIFIED BOOTSTRAP JQUERY ====================================================================================================================================--><script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>

<!--  MINIFIED BOOTSTRAP JAVASCRIPT ============================================================================================================================== --> 	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha256-KXn5puMvxCw+dAYznun+drMdG1IFl3agK0p/pqT9KAo= sha512-2e8qq0ETcfWRI4HJBzQiA3UoyFk6tbNyG+qSaIBZLyW9Xf3sWZHN/lxe9fTh1U45DpPf07yj94KsUHHWe4Yk1A==" crossorigin="anonymous"></script>

<!--  PLUGIN JAVASCRIPT ========================================================================================================================================== -->
    <script src="js/jquery.easing.min.js"></script>
    <script src="js/jquery.fittext.js"></script>
    <script src="js/wow.min.js"></script>

<!--  CUSTOM THEME JAVASCRIPT ==================================================================================================================================== -->
    <script src="js/creative.js"></script>

</body>

</html>
