<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="NOODP">
    <meta name="description" content="It's going to get a little crazy on this blog! I am a new father, loving husband, and stay at home 'fommy.' Join me on my journey as I discuss hot-button topics and re-tell the mostly humourous side of being a family-mant.">
    <meta name="keywords" content="blog, parent, father, fommy, stay at home, funny, humour, dad, newborn, baby, nursery, web development, tech">
    <meta name="author" content="Evan Marshall">
    <link rel="icon" href="#">

    <title>Giggles N Shit Blog</title>
    
    <!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
	<script type="application/ld+json">
		[ {
		  "@context" : "http://schema.org",
		  "@type" : "Product",
		  "name" : "Giggles N Shit Blog",
		  "url" : "http://www.gigglesnshit.com/"
		}, {
		  "@context" : "http://schema.org",
		  "@type" : "Product",
		  "name" : "Giggles N Shit",
		  "image" : [ "http://www.google.com/img/portfolio/hospital.jpg", "http://www.google.com/img/portfolio/family.jpg", "http://www.google.com/img/portfolio/poo-chair.jpg", "http://www.google.com/img/portfolio/daddys-girl.jpg", "http://www.google.com/img/portfolio/football.jpg", "http://www.google.com/img/portfolio/playpin.jpg" ],
		  "description" : "It&#39;s going to get a little crazy on this blog! I am a new father, loving husband, and stay at home &#39;fommy.&#39; Join me on my journey as I discuss hot-button topics and re-tell the mostly humourous side of being a family-man.",
		  "url" : "http://www.gigglesnshit.com/"
		} ]
	</script>

<!-- MINIFIED BOOTSTRAP CSS ====================================================================================================================================== -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet" integrity="sha256-7s5uDGW3AHqw6xtJmNNtr+OBRJUlgkNJEo78P4b0yRw= sha512-nNo+yCHEyn0smMxSswnf/OnX6/KwJuZTlNZBjauKhTK0c+zT+q5JOCx0UFhXQ6rJR9jg6Es8gPuD2uZcYDLqSw==" crossorigin="anonymous">

<!-- CUSTOM FONTS ================================================================================================================================================ -->
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic" rel="stylesheet" type="text/css">
    
<!-- FONT-AWESOME ================================================================================================================================================ -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha256-3dkvEK0WLHRJ7/Csr0BZjAWxERc5WH7bdeUya2aXxdU= sha512-+L4yy6FRcDGbXJ9mPG8MT/3UCDzwR9gPeyFNMCtInsol++5m3bk2bXWKdZjvybmohrAsn3Ua5x8gfLnbE1YkOg==" crossorigin="anonymous">
    
<!-- FAVICONS ==================================================================================================================================================== -->    
 	<link rel="apple-touch-icon" sizes="57x57" href="../img/favicon/apple-touch-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="../img/favicon/apple-touch-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="../img/favicon/apple-touch-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="../img/favicon/apple-touch-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="../img/favicon/apple-touch-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="../img/favicon/apple-touch-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="../img/favicon/apple-touch-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="../img/favicon/apple-touch-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="../img/favicon/apple-touch-icon-180x180.png">
    <link rel="icon" type="image/png" href="../img/favicon/favicon-32x32.png" sizes="32x32">
    <link rel="icon" type="image/png" href="../img/favicon/android-chrome-192x192.png" sizes="192x192">
    <link rel="icon" type="image/png" href="../img/favicon/favicon-96x96.png" sizes="96x96">
    <link rel="icon" type="image/png" href="../img/favicon/favicon-16x16.png" sizes="16x16">
    <link rel="manifest" href="../img/favicon/manifest.json">
    <link rel="mask-icon" href="../img/favicon/safari-pinned-tab.svg" color="#5763ac">
    <link rel="shortcut icon" href="../img/favicon/favicon.ico">
    <meta name="apple-mobile-web-app-title" content="GigglesNShit">
    <meta name="application-name" content="GigglesNShit">
    <meta name="msapplication-TileColor" content="#5763ac">
    <meta name="msapplication-TileImage" content="../img/favicon/mstile-144x144.png">
    <meta name="msapplication-config" content="../img/favicon/browserconfig.xml">
    <meta name="theme-color" content="#5763ac">

<!-- PLUGIN CSS ================================================================================================================================================== -->
    <link rel="stylesheet" href="../css/animate.min.css" type="text/css">

<!-- CUSTOM CSS ================================================================================================================================================== -->
    <link rel="stylesheet" href="../css/creative.css" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body id="page-top">

	<!-- google analytics -->
    <?php include_once("../php/analyticstracking.php") ?>
    
    <!-- Google Tag Manager -->
    <noscript>
    	<iframe src="//www.googletagmanager.com/ns.html?id=GTM-ND2TLM" height="0" width="0" style="display:none;visibility:hidden"></iframe>
    </noscript>
    <script>
		(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start': new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0], j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src= '//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);})(window,document,'script','dataLayer','GTM-ND2TLM');
    </script>
    <!-- End Google Tag Manager -->

    <nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <a class="navbar-brand page-scroll" href="../index.php">Giggles N Shit Blog</a>
            </div>
        </div>
        <!-- /.container-fluid -->
    </nav>

    <header>
        <div class="header-content">
            <div class="header-content-inner">
            	<?php
					include("../php/comment.php");
				?>
                <h1>Giggles N Shit</h1>
                <hr>
                <a href="https://www.instagram.com/gigglesnshitblog/" class="btn btn-primary btn-xl page-scroll">#gigglesnshitblog</a>
            </div>
        </div>
    </header>

    <section class="bg-primary" id="about">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 text-center">
                
                	<!-- google adsense ad -->
                    <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
                    <!-- Google Ad -->
                    <ins class="adsbygoogle"
                        style="display:block"
                        data-ad-client="ca-pub-8526023922334594"
                        data-ad-slot="7357456062"
                        data-ad-format="auto"></ins>
                    <script>
                        (adsbygoogle = window.adsbygoogle || []).push({});
                    </script><br><br>
                
                	<h2>"The Watermelon Incident..."</h2>
                    <h3 class="section-heading">March 28th 2016</h3>
                    <hr class="light">
                    
                        <p class="text-faded">Nine months of: "You'll want to pull your hair out!" Nine months of: "Crazy mood swings and cravings." When people find out you are going to become a parent, a grey cloud emerges in the sky, thunder crashes around you, a red haze fills the air and pure evil seems to indoctrinate anyone you speak to. "Once that miniature devil is born, say goodbye to your life as you know it and hello to the worse years of your life!" "That thing will ruin your wife's body and you will never sleep, have sex, or a peaceful moment again!" Really people? Is it really that bad or are you just boring and narcissistic about accomplishing such an amazing feat that you just HAVE to tell the world about how you survived it? Why the hell do people even start a family if it's so overwhelmingly difficult?</p>
    
                        <p class="text-faded">For all of you soon-to-be parents/spouses of a pregnant woman out there, I'm here to say: "it's really not that bad." Now I know some mothers have complicated pregnancies and some mothers lack support from a partner, so I understand there can be some truth in the negativity of pregnancy and birth. Fortunately Katie's first pregnancy was relatively straight forward (that doesn't mean there weren't funny situations throughout). In my opinion, even in some really shitty situations, I think it is all about your perspective. There is always a silver lining of positivity and humour even in the worst situations. I have observed the people who have told me the "horror stories" of pregnancy and raising a child, and to be honest I'm not surprised. Pacifying their children with a smartphone, sheltering their children from what's important in life (i.e. not allowing them to fail in school when they clearly are or the famous: everyone is a winner crap), not believing in discipline or saying "no" to their child, and buying into the next hippy-dippy parenting thing they read on Facebook (do you know people actually save their placentas and convert them into pill form for nutrition? Isn't that cannibalism??). Come on people, are you really surprised you're having a difficult time with parenting? "No Mr. Teacher (who has forty more years of maturing on this planet than my five year old) my son would never kick up sand into the face of some douchebag kid who stole his popcorn at recess." “Well guess what Mr. Parent, kids are little assholes and so were you when you were that age so get your head out of the clouds and let the poor teacher do his job.”  Isn't it our responsibility to provide care and love to our women carrying one of the most precious things in human creation for nine months (within reason... they aren't completely useless and you know they will milk it once in a while)? Isn't it our responsibility to let these innocent, underdeveloped creatures learn the ways of this cruel world with our guidance? One of my favourite sayings is: "un-coachable children grow up to be un-employable adults." Don't ask me who said that. I'm the type of person who forgets your name as soon as my hand leaves the handshake. The saying is so true though. I have seen it by watching parents and managing staff for years. Don't do that to your children people. It's more important to let your child screw something up and be there to show them how to fix it than to try and prevent them from ever making the mistake in the first place. That's just one rookie ginger father's opinion... Maybe I'll be wrong and I'm sure you'll hear about it on here.</p>
    
                        <p class="text-faded">Back to Katie and her fabulous belly. Katie and I probably piss people off once in a while about our health and nutrition craziness. We believe that the food we eat and how we cook it needs to be as close to the source as possible (except for Cadbury Mini Eggs... Mini Eggs are exempt). Maybe it's just a coincidence but people who know me know that I used to be a pretty intense athlete and in great shape. Then I went to university, quit competitive paddling and everything went to shit. The thing is, besides being a little squishier in the abdomen and breathing heavier going up a flight of stairs, I have managed to maintain the same weight for the last 10 years. I attribute that strongly to our diet. Anyways, I'm not going to bore you with a health and nutrition rant, I just wanted to mention that because it is what we believe made Katie's pregnancy pretty straight forward. You don’t have to drastically change your lifestyle when you’re pregnant unless your lifestyle includes sniffing bath salts, smoking crack or binge drinking with sororities on the weekends. It took forever for her belly to show, the mood swings were relatively non-existent (until the final month or so), there were no weird cravings (i.e. anchovies and Sour Patch Kids), she was still pretty active and generally pleasant to be around (mind blown?). We always got a kick out of how people become very inconsiderate when they make comments to a pregnant woman. For example: "Holy shit, you are getting huge." "Oh man, are you carrying twins?" Thank god Katie had some self esteem or I would have come home to her crying in the corner surrounded by a bunch of Lipozene cartons and chocolate bar wrappers. It is what I like to call "nonversation." Sorry, unfortunately I can't copyright that because I did not come up with it. Working in retail you develop a strong aversion to "nonversation." It is when people are so socially stunted that when they meet with you they can't carry a normal conversation and end up mustering: "so how about that weather out there, only in Nova Scotia eh?!" "Working hard or hardly working, muhahahah?" "Did you see that Montreal game last night? Leafs fans are laughing now I'm sure." I always stay professional in these dire situations even though I want to grab the nearest stapler, dip it in some vinegar, and... I'll let you figure out the rest of that sentence. Then you have those assholes who find out, I'm staying at home while Katie is going to bring home the bacon, saying things like: "That's the least he can do since you carried a baby for nine gruelling months (like I was some useless piece of shit, drooling while I  stared out into space for nine months)." Or the ones that look at you like you have pickles for ears while awkwardly saying: "Well, good for you (like I'm attempting to find the cure for cancer or something)." Well, telling a pregnant woman she is large is up there with some of the worst nonversation.</p>
    
                        <p class="text-faded">Now that I think about it, some of the worst parts of being pregnant are the other people. Hey, maybe her pregnancy went so well because her husband is so amazing and cautious (because he knew that one false move she would do as the Black Widow spider does). Well there were two such moments where I, in retrospect, may have slipped.</p> 
    
                        <h3 class="header-text">Moment #1: The Peanut Butter Burger Massacre</h3>
    
                        <p class="text-faded">This slip up was very early on (and I mean early). It was actually soon after the story of my last post. My wife wanted to keep the news of her being pregnant under lock and key until the end of first trimester (oh, in case you haven't realized, I hate the term "we" are pregnant it just makes me feel weird like I have to start wearing maternity clothes or something). I can understand why she felt this way, with the prevalence of miscarriages and not wanting to have to share such a loss with the world. I just think she kept forgetting that I had super sperm and “there ain't no way that was gonna happen…" Anyways, here we are (my best mate Josh and I), me just finding out I was going to have my first baby, super excited and my best friend had no idea. You know I had to tell him. Did I say this was only a few days after we found out from that bucket full of pregnancy tests? Josh and I were on our way to a quaint little restaurant in Halifax by the name of Darrell's. They are famous for their unsettlingly delicious "peanut butter burger." It is exactly as it sounds. The same as any other burger, dressed the way you want, with a glob of creamy smooth peanut butter on the bun. I was skeptical at first too, but Mmmmmm mmmmm. Josh and I are just arriving at the restaurant and decide to wait in the big ass lineup. Katie calls me and asks how things are going and for some stupid reason I decide to tell her that Josh wants to celebrate our news. She be all like: “News?! What news!? I am not even sure she took a breath throughout the next 10 minutes as she vocally abused me. It was so loud that the pair of dudes in front of us in line turned around and gave me the classic: duuuude, we are so sorry to hear you have been castrated, hopefully she is good in the sack, look. Once the peanut butter burger massacre was finished we joyously forgot the events of the past and mowed down our burgers in delight. Oh, you thought that was the end of it, hahahaha NO. Josh is like the Antwerp Diamond Centre Vault when it comes to keeping secrets. So much so that when I told him he absolutely could not tell anyone my news (for the sake of my well-being), he did not even tell his fiancee until she found out he didn’t. The secret-keeping-code he lives by is so ingrained that until this day I am sure he still doesn't understand why his now current wife was so upset (it was dicey whether or not they were even going to get married due to this… just kidding but seriously if you ever have a secret you need to get off your chest just talk to Josh). We all survived the peanut butter burger massacre and lived to tell the tale.</p>
    
                        <h3 class="header-text">Moment #2: The Watermelon Incident</h3>
    
                       	<p class="text-faded">So, we have finally arrived at the watermelon incident! Besides the very early slip-up, I did pretty good up until the last month of Katie’s pregnancy. During this time was when Katie started showing some of the more traditional pregnancy symptoms. Super tiredness, super hungriness (or as I likes to call it: prangry &copy), super absentmindedness (or as Josh likes to call it: placenta brain &copy), and super moodiness. I think the problem here was that I was getting used to how smooth the pregnancy was going that I slipped and fell into a pile of an argument with my plump-ripe wifey. It was such an un-important, stupid argument that neither one of us even remember what it was about (probably about whether or not Icelanders consume more Coca-Cola per Capita than any other nation). The premise of the argument is not important though, the events that unfolded next would change how I viewed pregnancy for the rest of my days. I tend to poke the bear when I get frustrated in an argument and say anything that will just set her off (I know: “Evan you are so much smarter than that”). This trait was even more of an issue when my beautiful wife couldn’t even bend over to put on her shoes. Needless to say, I poked mother bear while she was munching out on a watermelon, cut in half, in a tiny bowl. I was standing on the other side of the room and I saw the flames in her eyes, steam exiting her ears and it was in slow motion. The watermelon, bowl and all, floated ever so slightly into the air like a bullet followed by the small explosion of the gun powder. It zipped past my head with a whistling sound and exploded all over her Macbook and wall behind me. I was in so much shock that I went mute, put on my shoes and left to get cat litter so that our cats would love us again. There it is folks. That is the gist of Katie’ pregnancy. We both survived and are stronger because of it.</p>
    
                    	<h4>Peace out!</h4>
                        
    					<div class="thumbnail">
      						<img src="../img/portfolio/little-fam.jpg" alt="happy family">
      						<div class="caption">
                                <h3>Family Photo Shoot</h3>
                                <p>See, I told you we made it through pregnancy unscathed...</p>
      						</div>
						</div>
                </div>
            </div>
        </div>
    </section>
                
    <?php
		include("../php/comment-form.php");
	?>
    
    <?php
		include("../php/comment-display.php");
	?>

    <section id="contact">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 text-center">
                 	<h2 class="section-heading">Drop me a Line</h2>
                  	<hr class="primary">
                  	<p>Feel free to contact me anytime, anyday via my personal email or social media accounts.</p>
                    <div class="col-lg-12 text-center">
                        <i class="fa fa-envelope-o fa-3x wow bounceIn" data-wow-delay=".1s"></i>
                        <p><a href="mailto:evanmarshall1986@gmail.com">EMAIL ME!</a></p>
                    </div>
                    <div class="col-lg-3 col-xs-6 text-center">
                        <a href="https://www.facebook.com/gigglesnshitblog/"><i class="fa fa-facebook fa-3x wow bounceIn" data-wow-delay=".1s"></i></a>
                    </div>
                    <div class="col-lg-3 col-xs-6 text-center">
                        <a href="https://www.instagram.com/gigglesnshitblog/"><i class="fa fa-instagram fa-3x wow bounceIn" data-wow-delay=".1s"></i></a>
                    </div>
                    <div class="col-lg-3 col-xs-6 text-center">
                        <a href="https://www.etsy.com/ca/shop/BabyIslay?ref=shopinfo_shophome_leftnav"><i class="fa fa-shopping-cart fa-3x wow bounceIn" data-wow-delay=".1s"></i></a>
                    </div>
                    <div class="col-lg-3 col-xs-6 text-center">
                        <a href="https://www.pinterest.com/BabyIslay/"><i class="fa fa-pinterest fa-3x wow bounceIn" data-wow-delay=".1s"></i></a>
                    </div>
        		</div>
     		</div>
     	</div>
 	</section>
            
    <section id="admin" class="bg-dark">
        <div class="container">
            <div class="row">
                <div class="col-lg-4 col-xs-4">
                    <p>To update password click <a href="php/password.php">HERE</a></p>
             	</div>
            
            	<div class="text-center col-lg-4 col-xs-4">
            		<!-- Start of StatCounter Code for Dreamweaver -->
					<script type="text/javascript">
						var sc_project=10886934; 
						var sc_invisible=0; 
						var sc_security="c23d5ac3"; 
						var scJsHost = (("https:" == document.location.protocol) ?
						"https://secure." : "http://www.");
						document.write("<sc"+"ript type='text/javascript' src='" +scJsHost+ "statcounter.com/counter/counter.js'></"+"script>");
                	</script>
                	<noscript>
                		<div class="statcounter">
                    		<a title="shopify stats"href="http://statcounter.com/shopify/" target="_blank">
                        		<img class="statcounter"src="http://c.statcounter.com/10886934/0/c23d5ac3/0/" alt="shopify stats">
                     		</a>
                		</div>
             		</noscript>
                	<!-- End of StatCounter Code for Dreamweaver -->
    				<a href="http://statcounter.com/p10886934/?guest=1">View My Stats</a>
            	</div>
                <div class="text-center col-lg-4 col-xs-4">
                    <p>&copy; <a href="http://www.gigglesnshit.com">Giggles N Shit Blog</a> - 2016</p>
        		</div>
         	</div>
    	</div>
        <div class="embed-responsive embed-responsive-16by9" id="amazon">
     		<iframe class="embed-responsive-item" src="http://astore.amazon.ca/ginshbl-20" frameborder="0" scrolling="yes"></iframe>
      	</div>
        <div id="amazon-link" class="text-center text-capitalize">
        	<h2><a href="http://astore.amazon.ca/ginshbl-20">Giggles N Shit Must Haves</a></h2>
        </div>
    </section>


<!-- MINIFIED BOOTSTRAP JQUERY ====================================================================================================================================--><script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>

<!--  MINIFIED BOOTSTRAP JAVASCRIPT ============================================================================================================================== --> 	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha256-KXn5puMvxCw+dAYznun+drMdG1IFl3agK0p/pqT9KAo= sha512-2e8qq0ETcfWRI4HJBzQiA3UoyFk6tbNyG+qSaIBZLyW9Xf3sWZHN/lxe9fTh1U45DpPf07yj94KsUHHWe4Yk1A==" crossorigin="anonymous"></script>

<!--  PLUGIN JAVASCRIPT ========================================================================================================================================== -->
    <script src="../js/jquery.easing.min.js"></script>
    <script src="../js/jquery.fittext.js"></script>
    <script src="../js/wow.min.js"></script>

<!--  CUSTOM THEME JAVASCRIPT ==================================================================================================================================== -->
    <script src="../js/creative.js"></script>

</body>

</html>
