<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="NOODP">
    <meta name="description" content="It's going to get a little crazy on this blog! I am a new father, loving husband, and stay at home 'fommy.' Join me on my journey as I discuss hot-button topics and re-tell the mostly humourous side of being a family-mant.">
    <meta name="keywords" content="blog, parent, father, fommy, stay at home, funny, humour, dad, newborn, baby, nursery, web development, tech">
    <meta name="author" content="Evan Marshall">
    
    <!-- Facebook Graph Tags for Sharing Pages -->
    <meta property="og:url" content="http://www.gigglesnshit.com/pages/blog-3.php" />
    <meta property="og:type" content="website" />
    <meta property="og:title" content="Main Blog Page" />
    <meta property="og:description" content="It's going to get a little crazy on this blog! I am a new father, loving husband, and stay at home 'fommy.' Join me on my journey as I discuss hot-button topics and re-tell the mostly humourous side of being a family-man" />
    <meta property="og:image" content="http://www.gigglesnshit.com/img/portfolio/peanut.jpg" />
    <meta property="fb:app_id" content="970981369664540"/>
    <meta property="og:site_name" content="Giggles N Shit Blog"/>

    <title>Giggles N Shit Blog</title>
    
    <!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
	<script type="application/ld+json">
		[ {
		  "@context" : "http://schema.org",
		  "@type" : "Product",
		  "name" : "Giggles N Shit Blog",
		  "url" : "http://www.gigglesnshit.com/"
		}, {
		  "@context" : "http://schema.org",
		  "@type" : "Product",
		  "name" : "Giggles N Shit",
		  "image" : [ "http://www.google.com/img/portfolio/hospital.jpg", "http://www.google.com/img/portfolio/family.jpg", "http://www.google.com/img/portfolio/poo-chair.jpg", "http://www.google.com/img/portfolio/daddys-girl.jpg", "http://www.google.com/img/portfolio/football.jpg", "http://www.google.com/img/portfolio/playpin.jpg" ],
		  "description" : "It&#39;s going to get a little crazy on this blog! I am a new father, loving husband, and stay at home &#39;fommy.&#39; Join me on my journey as I discuss hot-button topics and re-tell the mostly humourous side of being a family-man.",
		  "url" : "http://www.gigglesnshit.com/"
		} ]
	</script>

<!-- MINIFIED BOOTSTRAP CSS ====================================================================================================================================== -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet" integrity="sha256-7s5uDGW3AHqw6xtJmNNtr+OBRJUlgkNJEo78P4b0yRw= sha512-nNo+yCHEyn0smMxSswnf/OnX6/KwJuZTlNZBjauKhTK0c+zT+q5JOCx0UFhXQ6rJR9jg6Es8gPuD2uZcYDLqSw==" crossorigin="anonymous">

<!-- CUSTOM FONTS ================================================================================================================================================ -->
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic" rel="stylesheet" type="text/css">
    
<!-- FONT-AWESOME ================================================================================================================================================ -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha256-3dkvEK0WLHRJ7/Csr0BZjAWxERc5WH7bdeUya2aXxdU= sha512-+L4yy6FRcDGbXJ9mPG8MT/3UCDzwR9gPeyFNMCtInsol++5m3bk2bXWKdZjvybmohrAsn3Ua5x8gfLnbE1YkOg==" crossorigin="anonymous">
    
<!-- FAVICONS ==================================================================================================================================================== -->    
 	<link rel="apple-touch-icon" sizes="57x57" href="../img/favicon/apple-touch-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="../img/favicon/apple-touch-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="../img/favicon/apple-touch-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="../img/favicon/apple-touch-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="../img/favicon/apple-touch-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="../img/favicon/apple-touch-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="../img/favicon/apple-touch-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="../img/favicon/apple-touch-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="../img/favicon/apple-touch-icon-180x180.png">
    <link rel="icon" type="image/png" href="../img/favicon/favicon-32x32.png" sizes="32x32">
    <link rel="icon" type="image/png" href="../img/favicon/android-chrome-192x192.png" sizes="192x192">
    <link rel="icon" type="image/png" href="../img/favicon/favicon-96x96.png" sizes="96x96">
    <link rel="icon" type="image/png" href="../img/favicon/favicon-16x16.png" sizes="16x16">
    <link rel="manifest" href="../img/favicon/manifest.json">
    <link rel="mask-icon" href="../img/favicon/safari-pinned-tab.svg" color="#5763ac">
    <link rel="shortcut icon" href="../img/favicon/favicon.ico">
    <meta name="apple-mobile-web-app-title" content="GigglesNShit">
    <meta name="application-name" content="GigglesNShit">
    <meta name="msapplication-TileColor" content="#5763ac">
    <meta name="msapplication-TileImage" content="../img/favicon/mstile-144x144.png">
    <meta name="msapplication-config" content="../img/favicon/browserconfig.xml">
    <meta name="theme-color" content="#5763ac">

<!-- PLUGIN CSS ================================================================================================================================================== -->
    <link rel="stylesheet" href="../css/animate.min.css" type="text/css">

<!-- CUSTOM CSS ================================================================================================================================================== -->
    <link rel="stylesheet" href="../css/creative.css" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body id="page-top">

	<!-- google analytics -->
    <?php include_once("../php/analyticstracking.php") ?>
    
    <!-- Facebook SDK -->
    <div id="fb-root"></div>
	<script>(function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.5&appId=970981369664540";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>
    
    <!-- Google Tag Manager -->
    <noscript>
    	<iframe src="//www.googletagmanager.com/ns.html?id=GTM-ND2TLM" height="0" width="0" style="display:none;visibility:hidden"></iframe>
    </noscript>
    <script>
		(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start': new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0], j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src= '//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);})(window,document,'script','dataLayer','GTM-ND2TLM');
    </script>
    <!-- End Google Tag Manager -->

    <nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <a class="navbar-brand page-scroll" href="../index.php">Giggles N Shit Blog</a>
            </div>
        </div>
        <!-- /.container-fluid -->
    </nav>

    <header>
        <div class="header-content">
            <div class="header-content-inner">
                <h1>Giggles N Shit</h1>
                <hr>
                <a href="https://www.instagram.com/gigglesnshitblog/" class="btn btn-primary btn-xl page-scroll">#gigglesnshitblog</a>
            </div>
        </div>
    </header>
    
    <section class="bg-dark">
    	<div class="container-fluid text-center">
        	<script>
				// This is called with the results from from FB.getLoginStatus().
				function statusChangeCallback(response) {
					console.log('statusChangeCallback');
					console.log(response);
					// The response object is returned with a status field that lets the
					// app know the current login status of the person.
					// Full docs on the response object can be found in the documentation
					// for FB.getLoginStatus().
						if (response.status === 'connected') {
							// Logged into your app and Facebook.
							testAPI();
						} else if (response.status === 'not_authorized') {
							// The person is logged into Facebook, but not your app.
							document.getElementById('status').innerHTML = 'Please log ' +
							'into this app.';
				} else {
					// The person is not logged into Facebook, so we're not sure if
					// they are logged into this app or not.
					document.getElementById('status').innerHTML = 'Please log ' +
					'into Facebook.';
					}
  				}

				// This function is called when someone finishes with the Login
				// Button.  See the onlogin handler attached to it in the sample
				// code below.
				function checkLoginState() {
					FB.getLoginStatus(function(response) {
						statusChangeCallback(response);
					});
				}

				window.fbAsyncInit = function() {
				FB.init({
					appId      : '970981369664540',
					cookie     : true,  // enable cookies to allow the server to access 
										// the session
					xfbml      : true,  // parse social plugins on this page
					version    : 'v2.5' // use graph api version 2.5
				});

				// Now that we've initialized the JavaScript SDK, we call 
				// FB.getLoginStatus().  This function gets the state of the
				// person visiting this page and can return one of three states to
				// the callback you provide.  They can be:
				//
				// 1. Logged into your app ('connected')
				// 2. Logged into Facebook, but not your app ('not_authorized')
				// 3. Not logged into Facebook and can't tell if they are logged into
				//    your app or not.
				//
				// These three cases are handled in the callback function.

				FB.getLoginStatus(function(response) {
					statusChangeCallback(response);
				});
				
				};

				// Load the SDK asynchronously
				(function(d, s, id) {
					var js, fjs = d.getElementsByTagName(s)[0];
					if (d.getElementById(id)) return;
					js = d.createElement(s); js.id = id;
					js.src = "//connect.facebook.net/en_US/sdk.js";
					fjs.parentNode.insertBefore(js, fjs);
				}(document, 'script', 'facebook-jssdk'));

				// Here we run a very simple test of the Graph API after login is
				// successful.  See statusChangeCallback() for when this call is made.
				function testAPI() {
					console.log('Welcome!  Fetching your information.... ');
					FB.api('/me', function(response) {
						console.log('Successful login for: ' + response.name);
						document.getElementById('status').innerHTML =
						'Thanks for logging in, ' + response.name + '!';
					});
				}
			</script>

			<!-- Facebook Login Button -->

			<fb:login-button scope="public_profile,email" onlogin="checkLoginState();"></fb:login-button>

			<div id="status"></div>

		</div>
	</section>

    <section class="bg-primary" id="about">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 text-center">
                
                	<!-- google adsense assigned to php variable -->
                    <?php
					
					$googleadsense = 
                    '<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
                    <!-- Google Ad -->
                    <ins class="adsbygoogle"
                        style="display:block"
                        data-ad-client="ca-pub-8526023922334594"
                        data-ad-slot="7357456062"
                        data-ad-format="auto"></ins>
                    <script>
                        (adsbygoogle = window.adsbygoogle || []).push({});
                    </script>';
					echo $googleadsense;
					
                    ?><br><br>
                
                	<h2>"The Bomb Drop: Part I"</h2>
                    <h3 class="section-heading">April 11<sup>th</sup>, 2016</h3>
                    <hr class="light">
                    
                        <p class="text-faded">So here we are. It is Monday April 11th (5 days before Katie's 28th birthday. Had to say that in this post as she never remembers her age and it is scary). It will be Isla's third trip to see her paediatrician. This Thursday will be her zillionth time seeing her GI specialist and blood clinic (I know, zillion is an exaggeration, but it's been a lot). The thing is, am I going to tell you why? Of course not! You will have to read on punk! Oooohhh, bomb drop, no he didn't? Yes he did! Title drop... I digress. </p>
    
                        <p class="text-faded">Let's start over. We left off with Katie spitting out a baby human from her Hoo Hah. Why not start there? We are now in the maternity unit at the Valley Regional Hospital and being treated like royalty for some reason (maybe it's because Katie is the big bad boss lady and scares the crap out of everyone? Maybe not...). Everything is going fairly smooth.  I mean, those fuckers don't sleep, but other than that everything is swell. We had regular visits from the paediatrician (not the one mentioned above, but the hospital one. I'll do my best to keep things straight for ya over the next couple of posts (there are a lot of professionals so keep up!). I know their job is important and all, but it seems the gist of what they do is come into your room while you are stress ridden and lacking sleep. Next, they mosey on over to your FINALLY sleeping baby, whip off their onesie, start poking at their bellies, rotating their legs ever so slightly, wake the damn baby up, and then leave the room with an evil chuckle. I'm just kidding, they're great. Isla had frequent visits from nurses and blood collection. She got her little heel poked and squeezed in order to check a battery of different things. She took that poke like a champ, too. That's important to me, because I'm the biggest pansy around when it comes to needles. I can handle blood, several broken bones, ruptured appendix, etc, but when that little sliver of metal pierces my body, this 6' 3" lug collapses like a ton of bricks. Yes I know, I'm a big baby. There's feeble little old ladies that go in on a regular basis whom are so cool with those torture devices that they almost take it from the technician’s hand and poke themselves. I had to have at least one flaw yah know!</p>
    
                        <p class="text-faded">It's amazing how long you can just stare at this wondrous creation of yours. I'm serious, MGM or Fox needs to jump on this opportunity and make a movie/time-lapse video of some random baby being a baby. That shit would be a hit!! We were in the hospital for two days. These two days felt a lot longer due to our sleeping arrangements. When you're sleeping on a rickety old cot made for a little person and a blanket that's basically the size of a bath towel; it ain’t fun. It was all worth it in the end, though, or at least we kept telling ourselves that... Flash forward to an extremely sleepless night during the first week we brought Isla home. She was fussy as all hell and we were at our wits end with ways to settle her. Both of us were sitting down, hair standing at its ends, panting, and Katie looks up at me to say: "I can't do this anymore." (by the way, Katie is someone who needs all of her sleep in order to function properly so you can imagine the shape she was in). I stood up and abruptly said: "Alright, pack up her things, let's give her back!" That's basically my role in our relationship and it has been working quite well for the last 12 years. When Katie is being a drama queen, I say something stupid to lighten the mood. </p>
    
                        <p class="text-faded">Flash back again to a few days prior to the day we were ready to enforce the return policy on Isla. We were at the hospital for our final day, full of anticipation to get the "all clear" for her routine tests and head home. Everything is how it should be. She is responsive, her belly pokes reveal normality, and she even had that disgusting amniotic poop (the one that looks like molasses (knew there was a reason I didn't trust molasses). The only concern they had was her bilirubin levels were on the high side of normal (hence the extra day at the hospital). For those of you who don’t know, bilirubin is the active part of your bile, which is secreted from your liver and into your small intestine. It’s main function is the break down of red blood cells and digestion of fat in your diet (by no means is that the medical definition, but it is my understanding. There will be more laymen's definitions to come as we have had many’a learnings over the last few months). That's fairly normal though and even if her levels didn't drop they would just give her her first trip to the tanning bed and say goodbye to her newborn jaundice. Long story short, the bilirubin levels did drop and we were released that day. We bundled her up in her car seat like an easily bruised kiwi, carried her out to the SUV like she would shatter if dropped, and headed home to our new normal! </p> 
    
                        <p class="text-faded">We learned that at a few days old Isla was definitely a princess. When putting her down for a nap she needed the following: tightly wrapped swaddle blanket (see my "must haves” section below, they are freakin' awesome and fairly priced), a perfect temperature of 26 to 28 degrees Celsius, near pitch black room, and constant white noise (also in my “must haves” section). If any of those variables are missing you can pretty much kiss your sleep goodbye. Katie's genes definitely kicked the shit out of my rare Ginger Genes. Luckily Isla got her mothers deep brown eyes, darker complexion, brown hair (what little of it she has), and a mini-me face of her mother. Come to think of it, if it wasn't for how long that baby was, I would have bene looking for a paternity test. Either Katie hooked up with the Purolator man or Isla just asexually budded off of her mother.  </p>
                        
                        <div class="thumbnail">
      						<img src="../img/portfolio/side-by-side.jpg" alt="comparison">
      						<div class="caption">
                                <h3>Who is Who?</h3>
                                <p>Top-Left: Katie at 1 year, Top-Right: Isla at 3 months, Bottom-Left: Me at 8 months, Bottom-Right: A Face Swap of Isla and I.</p>
      						</div>
						</div>
    
                       	<p class="text-faded">
Katie had researched just about everything baby related prior to Isla's arrival. She even looked up a very descriptive  and picturesque step by step guide to how poop colour/texture should look at all stages of a babies' life (I thought it was gross, but I have learned now how important this is, so make sure you know your babies' poop!). We were a little over a month in and starting to get into a good routine with our baby girl. The first two weeks were a shit show, but it's surprising how innately parenting is just picked up. So all of you soon-to-be parents out there, take it from me, things will work out just fine. We were starting to have some concerns however. Isla's jaundice wasn't decreasing in her skin and the sclera of her eyes (that’s the white part of your eyes). Her poop wasn't the bright yellow colour we were expecting, but was in fact quite pale-grey. She wasn't gaining weight as quickly as the baby growth chart was expecting (parents, make sure you are keeping an eye on all of these milestones of a newborn. Parents will always know best, but you need to do a little research with the guidance of your doctor). The lack of growth was a tough one as Katie and I believed strongly in the benefits of exclusive breastfeeding, but unfortunately had to make the compromise of supplementing with formula. We still didn't go exclusively to formula, which I thought was a good compromise. It seemed that Isla agreed as well, since it helped her growth get back on track and even helped her sleep longer at night. Because breastfeeding jaundice is quite common and she was back to normal growth, our family doctor wasn't too concerned with Isla's progression. Thank god Katie was so obsessed with Isla's poop as you will soon understand! As soon as that waft of pleasant odour reached Katie's nose (from up to a mile away), you would hear her feet drop to the floor and she would run towards me to tackle the diaper out of my hand for inspection. If it wasn't for the poop inspection, our family doctor never would have referred us to a local paediatrician (who goes above and beyond any health professional I've ever met. Amazing dude), and we never would have made it to our newest normal with Isla. </p>
                        
                        <p class="text-faded">Ok, I'm finally going to tell you. Hopefully the suspense is unbearable now for you, my lovely readers, who do not know our family personally (I know, leading you on like this was a dick move, but we have made it). It was mid December 2015. Isla was just over a month old. I was working in the city and Katie was in the midst of her 4 months maternity leave (we decided I'd take the remaining 8 months, hence the term Fommy. Best decision of my life). It was the day Katie brought Isla in to see her paediatrician. It was about 6:30 pm when I got home from work and Katie had waited for me to arrive home before telling me how the doctor’s visit went. I remember walking in the door and seeing Katie holding our sweet baby girl tightly with tears in her eyes. She said the meeting did not go so well. Our whole lives we have been extremely fortunate so I always assume the best outcome, which makes it that much harder to hear bad news for once. However, we knew someday it was bound to happen. The paediatrician agreed that the jaundice and pale coloured poop was concerning. He advised Katie to head to the Valley Regional Hospital that day and get blood work done. He told us that there could be several reasons for these symptoms, but he wanted to rule out the most serious one, which is a dandy little disease called Biliary Atresia. This is where we learned that our paediatrician was a god send and he takes his career to a whole new level of awesomeness. He called Katie after hours to share with her the abnormal blood results and he called multiple times afterwards to ensure we were doing ok as well as having all of our questions answered. Our doctor presumed, with the risk of Biliary Atresia, that we would be admitted into the IWK Children's Hospital in Halifax. Unfortunately, he was correct and we took a trip to the hospital a couple days after the blood was drawn. </p>
                        
                        <p class="text-faded">You will soon see that our little Bambino is one tough SOB and she was damn good at getting me off work, un-planned (arriving a week early and now with a potential health issue). I would prefer to get off work for other reasons, but thank you dear. The holidays were now creeping up, we had just been admitted to the IWK (the bomb hasn't been dropped yet), and we don't even realize how our lives will change, yet again.</p>
                        
                </div>
            </div>
        </div>
    </section>
    
    <section class="bg-dark">    
        <div class="container-fluid">        
            <div class="fb-comments" data-order-by="social" data-mobile="auto-detected" data-colorscheme="dark" data-href="http://www.gigglesnshit.com/pages/blog-4.php" data-width="100%" data-numposts="10"></div>
        </div>
    </section>
    
    <section id="contact">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 text-center">
                 	<h2 class="section-heading">Drop me a Line</h2>
                  	<hr class="primary">
                  	<p>Feel free to contact me anytime, anyday via my personal email or social media accounts.</p>
                    <div class="col-lg-12 text-center">
                        <i class="fa fa-envelope-o fa-3x wow bounceIn" data-wow-delay=".1s"></i>
                        <p><a href="mailto:evanmarshall1986@gmail.com">EMAIL ME!</a></p>
                    </div>
                    <div class="col-lg-3 col-xs-6 text-center">
                        <a href="https://www.facebook.com/gigglesnshitblog/"><i class="fa fa-facebook fa-3x wow bounceIn" data-wow-delay=".1s"></i></a>
                    </div>
                    <div class="col-lg-3 col-xs-6 text-center">
                        <a href="https://www.instagram.com/gigglesnshitblog/"><i class="fa fa-instagram fa-3x wow bounceIn" data-wow-delay=".1s"></i></a>
                    </div>
                    <div class="col-lg-3 col-xs-6 text-center">
                        <a href="https://www.etsy.com/ca/shop/BabyIslay?ref=shopinfo_shophome_leftnav"><i class="fa fa-shopping-cart fa-3x wow bounceIn" data-wow-delay=".1s"></i></a>
                    </div>
                    <div class="col-lg-3 col-xs-6 text-center">
                        <a href="https://www.pinterest.com/BabyIslay/"><i class="fa fa-pinterest fa-3x wow bounceIn" data-wow-delay=".1s"></i></a>
                    </div>
                    
                    <!-- facbook like and share -->
                    <div class="col-lg-12 text-center" style="padding-top:20px;">
                        <div class="fb-like" data-href="https://www.gigglesnshit.com/pages/blog-3.php" data-layout="button_count" data-action="like" data-show-faces="true" data-share="true"></div>
                        <div class="fb-send" data-href="https://www.gigglesnshit.com/pages/blog-3.php"></div>
                    </div>
                    
        		</div>
     		</div>
     	</div>
 	</section>
            
    <section id="admin" class="bg-dark">
        <div class="container-fluid">
        	<div id="amazon-link" class="text-center text-capitalize">
                <h2 style="padding-bottom:15px;"><a href="http://astore.amazon.ca/ginshbl-20">Giggles N Shit Must Haves</a></h2>
                <div class="embed-responsive embed-responsive-16by9" id="amazon">
                    <iframe class="embed-responsive-item" src="http://astore.amazon.ca/ginshbl-20" frameborder="0" scrolling="yes"></iframe>
      			</div>
            </div>
            <div class="row" style="padding-top:15px;">
                <div class="text-center col-lg-12 col-xs-12">
                    <p>&copy; <a href="http://www.gigglesnshit.com">Giggles N Shit Blog</a> - 2016</p>
        		</div>
         	</div>
    	</div>
  	</section>

<!-- MINIFIED BOOTSTRAP JQUERY ====================================================================================================================================--><script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>

<!--  MINIFIED BOOTSTRAP JAVASCRIPT ============================================================================================================================== --> 	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha256-KXn5puMvxCw+dAYznun+drMdG1IFl3agK0p/pqT9KAo= sha512-2e8qq0ETcfWRI4HJBzQiA3UoyFk6tbNyG+qSaIBZLyW9Xf3sWZHN/lxe9fTh1U45DpPf07yj94KsUHHWe4Yk1A==" crossorigin="anonymous"></script>

<!--  PLUGIN JAVASCRIPT ========================================================================================================================================== -->
    <script src="../js/jquery.easing.min.js"></script>
    <script src="../js/jquery.fittext.js"></script>
    <script src="../js/wow.min.js"></script>

<!--  CUSTOM THEME JAVASCRIPT ==================================================================================================================================== -->
    <script src="../js/creative.js"></script>

</body>

</html>
