<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="NOODP">
    <meta name="description" content="It's going to get a little crazy on this blog! I am a new father, loving husband, and stay at home 'fommy.' Join me on my journey as I discuss hot-button topics and re-tell the mostly humourous side of being a family-mant.">
    <meta name="keywords" content="baby products, baby, baby's, baby wear, baby clothing, parent portal, parents, infant, newly baby, newborn baby, liver, disease, liver disease, biliary atresia, giggles, shit, giggles n shit, blog, parent, father, fommy, stay at home, funny, humour, dad, newborn, baby, nursery, web development, tech">
    <meta name="author" content="Evan Marshall">
    
    <!-- Facebook Graph Tags for Sharing Pages -->
    <meta property="og:url" content="http://www.gigglesnshit.com/pages/blog-3.php" />
    <meta property="og:type" content="website" />
    <meta property="og:title" content="Dr. Sloth" />
    <meta property="og:description" content="It's going to get a little crazy on this blog! I am a new father, loving husband, and stay at home 'fommy.' Join me on my journey as I discuss hot-button topics and re-tell the mostly humourous side of being a family-man" />
    <meta property="og:image" content="http://www.gigglesnshit.com/img/build/portfolio/peanut.jpg" />
    <meta property="fb:app_id" content="970981369664540"/>
    <meta property="og:site_name" content="Giggles N Shit Blog"/>

    <title>Giggles N Shit Blog</title>
    
    <!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
	<script type="application/ld+json">
		[ {
		  "@context" : "http://schema.org",
		  "@type" : "Product",
		  "name" : "Giggles N Shit Blog",
		  "url" : "http://www.gigglesnshit.com/"
		}, {
		  "@context" : "http://schema.org",
		  "@type" : "Product",
		  "name" : "Giggles N Shit",
		  "image" : [ "http://www.google.com/img/portfolio/hospital.jpg", "http://www.google.com/img/portfolio/family.jpg", "http://www.google.com/img/portfolio/poo-chair.jpg", "http://www.google.com/img/portfolio/daddys-girl.jpg", "http://www.google.com/img/portfolio/football.jpg", "http://www.google.com/img/portfolio/playpin.jpg" ],
		  "description" : "It&#39;s going to get a little crazy on this blog! I am a new father, loving husband, and stay at home &#39;fommy.&#39; Join me on my journey as I discuss hot-button topics and re-tell the mostly humourous side of being a family-man.",
		  "url" : "http://www.gigglesnshit.com/"
		} ]
	</script>

<!-- MINIFIED BOOTSTRAP CSS ====================================================================================================================================== -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet" integrity="sha256-7s5uDGW3AHqw6xtJmNNtr+OBRJUlgkNJEo78P4b0yRw= sha512-nNo+yCHEyn0smMxSswnf/OnX6/KwJuZTlNZBjauKhTK0c+zT+q5JOCx0UFhXQ6rJR9jg6Es8gPuD2uZcYDLqSw==" crossorigin="anonymous">

<!-- CUSTOM FONTS ================================================================================================================================================ -->
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic" rel="stylesheet" type="text/css">
    
<!-- FONT-AWESOME ================================================================================================================================================ -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha256-3dkvEK0WLHRJ7/Csr0BZjAWxERc5WH7bdeUya2aXxdU= sha512-+L4yy6FRcDGbXJ9mPG8MT/3UCDzwR9gPeyFNMCtInsol++5m3bk2bXWKdZjvybmohrAsn3Ua5x8gfLnbE1YkOg==" crossorigin="anonymous">
    
<!-- FAVICONS ==================================================================================================================================================== -->    
 	<link rel="apple-touch-icon" sizes="57x57" href="../img/build/favicon/apple-touch-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="../img/build/favicon/apple-touch-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="../img/build/favicon/apple-touch-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="../img/build/favicon/apple-touch-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="../img/build/favicon/apple-touch-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="../img/build/favicon/apple-touch-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="../img/build/favicon/apple-touch-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="../img/build/favicon/apple-touch-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="../img/build/favicon/apple-touch-icon-180x180.png">
    <link rel="icon" type="image/png" href="../img/build/favicon/favicon-32x32.png" sizes="32x32">
    <link rel="icon" type="image/png" href="../img/build/favicon/android-chrome-192x192.png" sizes="192x192">
    <link rel="icon" type="image/png" href="../img/build/favicon/favicon-96x96.png" sizes="96x96">
    <link rel="icon" type="image/png" href="../img/build/favicon/favicon-16x16.png" sizes="16x16">
    <link rel="manifest" href="../img/build/favicon/manifest.json">
    <link rel="mask-icon" href="../img/build/favicon/safari-pinned-tab.svg" color="#5763ac">
    <link rel="shortcut icon" href="../img/build/favicon/favicon.ico">
    <meta name="apple-mobile-web-app-title" content="GigglesNShit">
    <meta name="application-name" content="GigglesNShit">
    <meta name="msapplication-TileColor" content="#5763ac">
    <meta name="msapplication-TileImage" content="../img/build/favicon/mstile-144x144.png">
    <meta name="msapplication-config" content="../img/build/favicon/browserconfig.xml">
    <meta name="theme-color" content="#5763ac">

<!-- PLUGIN CSS ================================================================================================================================================== -->
    <link rel="stylesheet" href="../css/animate.min.css" type="text/css">

<!-- CUSTOM CSS ================================================================================================================================================== -->
    <link rel="stylesheet" href="../css/creative.css" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body id="page-top">

	<!-- google analytics -->
    <?php include_once("../php/analyticstracking.php") ?>
    
    <!-- Facebook SDK -->
    <div id="fb-root"></div>
	<script>(function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.5&appId=970981369664540";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>
    
    <!-- Google Tag Manager -->
        <noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-ND2TLM"
        height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
        <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
        new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
        j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
        '//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
        })(window,document,'script','dataLayer','GTM-ND2TLM');</script>
    <!-- End Google Tag Manager -->

    <nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <a class="navbar-brand page-scroll" href="../index.php" style="border:1px solid white;">Giggles N Shit Blog</a>
            </div>
        </div>
        <!-- /.container-fluid -->
    </nav>

    <header>
        <div class="header-content">
            <div class="header-content-inner">
                <h1>Giggles N Shit</h1>
                <hr>
                <a href="https://www.instagram.com/gigglesnshitblog/" class="btn btn-primary btn-xl page-scroll">#gigglesnshitblog</a>
            </div>
        </div>
    </header>
    
    <section class="bg-dark">
    	<div class="container-fluid text-center">
        	<script>
				// This is called with the results from from FB.getLoginStatus().
				function statusChangeCallback(response) {
					console.log('statusChangeCallback');
					console.log(response);
					// The response object is returned with a status field that lets the
					// app know the current login status of the person.
					// Full docs on the response object can be found in the documentation
					// for FB.getLoginStatus().
						if (response.status === 'connected') {
							// Logged into your app and Facebook.
							testAPI();
						} else if (response.status === 'not_authorized') {
							// The person is logged into Facebook, but not your app.
							document.getElementById('status').innerHTML = 'Please log ' +
							'into this app.';
				} else {
					// The person is not logged into Facebook, so we're not sure if
					// they are logged into this app or not.
					document.getElementById('status').innerHTML = 'Please log ' +
					'into Facebook.';
					}
  				}

				// This function is called when someone finishes with the Login
				// Button.  See the onlogin handler attached to it in the sample
				// code below.
				function checkLoginState() {
					FB.getLoginStatus(function(response) {
						statusChangeCallback(response);
					});
				}

				window.fbAsyncInit = function() {
				FB.init({
					appId      : '970981369664540',
					cookie     : true,  // enable cookies to allow the server to access 
										// the session
					xfbml      : true,  // parse social plugins on this page
					version    : 'v2.5' // use graph api version 2.5
				});

				// Now that we've initialized the JavaScript SDK, we call 
				// FB.getLoginStatus().  This function gets the state of the
				// person visiting this page and can return one of three states to
				// the callback you provide.  They can be:
				//
				// 1. Logged into your app ('connected')
				// 2. Logged into Facebook, but not your app ('not_authorized')
				// 3. Not logged into Facebook and can't tell if they are logged into
				//    your app or not.
				//
				// These three cases are handled in the callback function.

				FB.getLoginStatus(function(response) {
					statusChangeCallback(response);
				});
				
				};

				// Load the SDK asynchronously
				(function(d, s, id) {
					var js, fjs = d.getElementsByTagName(s)[0];
					if (d.getElementById(id)) return;
					js = d.createElement(s); js.id = id;
					js.src = "//connect.facebook.net/en_US/sdk.js";
					fjs.parentNode.insertBefore(js, fjs);
				}(document, 'script', 'facebook-jssdk'));

				// Here we run a very simple test of the Graph API after login is
				// successful.  See statusChangeCallback() for when this call is made.
				function testAPI() {
					console.log('Welcome!  Fetching your information.... ');
					FB.api('/me', function(response) {
						console.log('Successful login for: ' + response.name);
						document.getElementById('status').innerHTML =
						'Thanks for logging in, ' + response.name + '!';
					});
				}
			</script>

			<!-- Facebook Login Button -->

			<fb:login-button scope="public_profile,email" onlogin="checkLoginState();"></fb:login-button>

			<div id="status"></div>

		</div>
	</section>

    <section class="bg-primary" id="about">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 text-center">
                
                	<!-- google adsense assigned to php variable -->
                    <?php
					
					$googleadsense = 
                    '<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
                    <!-- Google Ad -->
                    <ins class="adsbygoogle"
                        style="display:block"
                        data-ad-client="ca-pub-8526023922334594"
                        data-ad-slot="7357456062"
                        data-ad-format="auto"></ins>
                    <script>
                        (adsbygoogle = window.adsbygoogle || []).push({});
                    </script>';
					echo $googleadsense;
					
                    ?><br><br>
                
                	<h2>"Dr. Sloth..."</h2>
                    <h3 class="section-heading">April 5<sup>th</sup>, 2016</h3>
                    <hr class="light">
                    
                        <p class="text-faded">Let's recap: We had an awkward butt wiping, we had a Halloween-long-John reception, we had watermelons flying and a peanut butter burgers feast. Now we are finally here. We are at the day that you know is coming, you try to prepare for, but always end up in a bag full-o-emotions. Labour Day, and not the fun one.</p>
    
                        <p class="text-faded">Leading up to Labour Day was like those stupid Facebook videos with the beautiful rolling hills, somber Irish background music, with a car leisurely coasting through the twisty turns (you know what's coming but not sure when) and then BAM! An ugly zombie-looking monster pops up in your field of view just to startle you. Except in this instance no zombie creature pops up. It is a goopy and alien-like creature, but I wouldn't say a zombie. </p>
    
                        <p class="text-faded">We knew it was getting down to the crunch. Katie had finally taken work off due to her swollen kankles and due to falling asleep while face to face with staff members during a conversation. It was three weeks before her due date and we were anxiously awaiting our little bambino's arrival. </p>
    
                        <p class="text-faded">We made it to about a week prior to the due date. November 10<sup>th</sup> 2015. We had a little bag prepared (not too much packed since we live about 1 minute away from the hospital or Katie's place of work), our minds were prepared and we knew we were going to be having a long day. People had gone from asking me how Katie was doing once a week to asking a couple times a day. It got to the point where I simply responded by saying: "If you see me run out of here like someone just told me my house was broken into (this actually happened), then you know how she's doing." Did I mention I work an hour away from home as well as the hospital? (I know eh, Katie drew the longer straw, but you can get the princess out of the castle but you can't get the princess out of the girl... Not sure if that makes any sense but it's provocative eh?) Luckily I did not need to turn my 2009 Hyundai Elantra into a NASCAR and Labour Day came while we were both at home. </p> 
    
                        <p class="text-faded">Just a note to all of you "new to being fathers" out there: When your wife invites you into the bathroom, when she is within a week of her due date, it is not for a party if you know what I mean... Katie had just finished her shower and called for me while I was still in bed sleeping. She was startled by some fluid running down her leg in the shower, which she was pretty sure wasn't the shower water or pee (who knows, she might be one of those gross people who let the bladder rip in the shower). She simply said: "Babe, I think I've gone into labour." Skadoosh! I was ready for this day. I had read all of the online blogs about how to support your wife during labour, I had my camera ready for the "belfie" (again, I unfortunately can't copyright that beautiful word), I did my morning push-ups for a month, and stretched on the hour. </p>
                        
                        <p>Check out the <a href="http://www.buzzfeed.com/stephaniemcneal/but-first-let-me-take-a-selfie#.kcrvVr23P" style="color:black;"><strong>article</strong></a> on the birth-selfie it's kind of funny.</p>
    
                       	<p class="text-faded">Not very much of the aforementioned things were true. I know you are shocked that I did not do daily push-ups, but it's true, I'm just blessed with this perfect body naturally (I did read up on supporting wifey during labour, but I'm not even sure the bag came with us to the hospital). So here's the life lesson I learned on Labour Day: You can plan all you want, not much if any of it will actually happen, just be there.</p>
                        
                        <p class="text-faded">Everything was pretty low key at this moment. I think I even saw a glimmer of hope in Katie's eyes: “Hey, if this is the pain, I don't know what all of those pansy mothers have been bitching about all of these years." We hopped into our SUV and began the 1 minute journey to the hospital. I learned, once we got there, that false alarms are a common occurrence because everyone was pretty chill. No one was dropping everything they were doing to push the pregnant lady to the ER, while punching out anyone who got in the way (you know like on the TV shows).</p>
                        
                        <p class="text-faded">No, it was all pretty straight forward. Obviously Katie's labour was going to be just as straight forward as her pregnancy, less those couple moments mentioned in my last post. They completed the fluid test and confirmed that "yes" her water broke. They hooked her up to the machine from ancient times, which spits out what you would see on a Richter scale, to time her contractions. Not much has changed in this medical technology... I mean hey, some crazy women are popping those little creatures out in their home bathtub. We got moved to the labour and delivery room as the contractions gradually got stronger and as Katie's look of: “Pssh, this is going to be a breeze" slowly turned into: “Damn, this shit hurts." </p>
                        
                        <p class="text-faded">Katie wanted to try to do things as natural as possible. No pain medication,  no cesarean section, no epidural, etc. I, as well as everyone else, respected that even though we were all thinking: “Good luck with that." Once you are feeling the pain of birth and you know the good stuff (medication) is in the next room, it is amazing how quickly your morals change. I have to hand it to her though; she stuck to her guns for the most part. Besides an occasional shot of Fentanyl and sucking on the gas mask like you suck on a Freezie to get the last remnants of that beautifully sweet surprise at the end; she held in there. She’s one tough mo fo. </p>
                        
                        <p class="text-faded">One more tip for all of you soon-to-be parents out there: There is no time in which you can't have an epidural (we learned this after the fact). Some staff will fight you on it because it can slow things down, which can be risky, but if you want it you go girlfriend! Well, Katie did eventually want it. When you're in enough pain and you've gained a tolerance to the gas, you will do anything to get rid of the pain. You don't care that there is a room full of people looking directly at your goodies. You don't care about the trauma that will be done to your taco. You don't care that you just mentally scarred that poor resident for sticking her fingers in your already stretched petunia. JUST... GET... ME... THAT... EPIDURAL!</p>
                        
                        <p class="text-faded">We finally convinced them to allow the epidural to happen. Here is something you don't want to hear when you get to this stage of labour and they wheel in the "epidural kit," (which looks just like that red metal tool box my father in law has in his garage, with a sticker label on it): "Well ok, we just want to warn you, the doctor is very particular and he likes to explain everything thoroughly before starting." "So he's slow as fuck?!" Well slow is an understatement. That dickhead was so slow he didn't even show up. He's probably still on his way to Isla's birth, five months later!</p>
                        
                        <p class="text-faded">Needless to say, Katie, unintentionally did not get to enjoy the pleasures of birth offered by the glorious epidural. Her labour started progressing to the point of no return. Isla was ready to see the world! Isla's heart rate was dropping with each contraction, in line with Katie's possessed screams to the holy hell. They wasted no time and attached the heart rate monitor to Isla's head (did you know they actually screw this into her head?! That shit is messed up!). They got Katie's OBGYN into the room followed by the torturer (poor resident), followed by a team of paediatricians. So you knew it was game time. They attached a suction to Isla's head in order to assist with Katie's pushing. I think 50 people’s faces and hands were all up in Katie's business at this point. Between you-me, you feel pretty useless as a husband in this room. I guess besides the back rubs and consoling, while your wife is on all fours pushing a human into the world, you feel pretty inadequate. It all happened pretty quickly now. One snip, one push, one Doctor yanking at your baby, one wide-eyed husband rocking in the corner and POP! Out comes what is the greatest blessing of your life. </p>
                        
                        <p class="text-faded">Katie was cute in this moment and looked up at me to ask how I was doing to which I just laughed and incredulously said: "how am I doing?!" I'm a pretty calm cool and collected guy who shows little emotion, but when that baby was handed to me I was a bubbling basket of emotions. I don't know if it was happiness or relief that my hand might regain feeling again one day. Just as quickly as the room filled, it was empty again. The room did not look as if life had been brought into it, but actually quite the contrary. There were blood smears on the floor, stains of every shade on the blankets, a panting pain relieved mother on the bed, and a father in the corner who could not stop staring at his creation. Even with all of that we still managed to snap a few pics of our little girl for the herds of friends and family anxiously waiting (make sure you follow Giggles N Shit Blog on <a href="https://www.facebook.com/gigglesnshitblog/">Facebook</a> and <a href="https://www.instagram.com/gigglesnshitblog/">Instagram</a> so you don't miss any of these pics). </p>
                        
                        <p class="text-faded">I always said newborn babies looked like a combination of alien and red jelly bellies, but when it's your own child you're "blinded by the light, revved up like a douche and running through the night" (I know those aren't the right lyrics but great song nonetheless). Your child always looks beautiful, but now looking at pictures before and after, she definitely looked like my little cherry jelly bean. </p>
                        
                        <p class="text-faded">I am still amazed at how much you love that little peanut instantly. I've never had it hit me right away like that. With a spouse it takes time and effort. With family you know you have to love them no matter what. I don't believe in all of the Hollywood fairy tale bullshit of love at first sight, fate, etc, but I have to say with Isla it was definitely love at first site. </p>
                        
                        <p><h3>And so Isla's story begins! Weighing in at 7 pounds 1 ounce, and arriving at approximately 4 pm, on November 10<sup>th</sup>, 2015. </h3></p>
                        
                        <p class="text-faded"><strong>P.S.</strong> I now understand why we have no recollection of our births. That shit is traumatic.</p>
                        
                </div>
            </div>
        </div>
    </section>
    
    <section class="bg-dark">    
        <div class="container-fluid">        
            <div class="fb-comments" data-order-by="social" data-mobile="auto-detected" data-colorscheme="dark" data-href="http://www.gigglesnshit.com/pages/blog-3.php" data-width="100%" data-numposts="10"></div>
        </div>
    </section>
    
    <section id="contact">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 text-center">
                 	<h2 class="section-heading">Drop me a Line</h2>
                  	<hr class="primary">
                  	<p>Feel free to contact me anytime, anyday via my personal email or social media accounts.</p>
                    <div class="col-lg-12 text-center">
                        <i class="fa fa-envelope-o fa-3x wow bounceIn" data-wow-delay=".1s"></i>
                        <p><a href="mailto:evanmarshall1986@gmail.com">EMAIL ME!</a></p>
                    </div>
                    <div class="col-lg-3 col-xs-6 text-center">
                        <a href="https://www.facebook.com/gigglesnshitblog/"><i class="fa fa-facebook fa-3x wow bounceIn" data-wow-delay=".1s"></i></a>
                    </div>
                    <div class="col-lg-3 col-xs-6 text-center">
                        <a href="https://www.instagram.com/gigglesnshitblog/"><i class="fa fa-instagram fa-3x wow bounceIn" data-wow-delay=".1s"></i></a>
                    </div>
                    <div class="col-lg-3 col-xs-6 text-center">
                        <a href="https://www.etsy.com/ca/shop/BabyIslay?ref=shopinfo_shophome_leftnav"><i class="fa fa-shopping-cart fa-3x wow bounceIn" data-wow-delay=".1s"></i></a>
                    </div>
                    <div class="col-lg-3 col-xs-6 text-center">
                        <a href="https://www.pinterest.com/BabyIslay/"><i class="fa fa-pinterest fa-3x wow bounceIn" data-wow-delay=".1s"></i></a>
                    </div>
                    
                    <!-- facbook like and share -->
                    <div class="col-lg-12 text-center" style="padding-top:20px;">
                        <div class="fb-like" data-href="https://www.gigglesnshit.com/pages/blog-3.php" data-layout="button_count" data-action="like" data-show-faces="true" data-share="true"></div>
                        <div class="fb-send" data-href="https://www.gigglesnshit.com/pages/blog-3.php"></div>
                    </div>
                    
        		</div>
     		</div>
     	</div>
 	</section>
            
    <section id="admin" class="bg-dark">
        <div class="container-fluid">
        	<div id="amazon-link" class="text-center text-capitalize">
                <h2 style="padding-bottom:15px;"><a href="http://astore.amazon.ca/ginshbl-20">Giggles N Shit Must Haves</a></h2>
                <div class="embed-responsive embed-responsive-16by9" id="amazon">
                    <iframe class="embed-responsive-item" src="http://astore.amazon.ca/ginshbl-20" frameborder="0" scrolling="yes"></iframe>
      			</div>
            </div>
            <div class="row" style="padding-top:15px;">
                <div class="text-center col-lg-12 col-xs-12">
                    <p>&copy; <a href="http://www.gigglesnshit.com">Giggles N Shit Blog</a> - 2016</p>
        		</div>
         	</div>
    	</div>
  	</section>

<!-- MINIFIED BOOTSTRAP JQUERY ====================================================================================================================================--><script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>

<!--  MINIFIED BOOTSTRAP JAVASCRIPT ============================================================================================================================== --> 	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha256-KXn5puMvxCw+dAYznun+drMdG1IFl3agK0p/pqT9KAo= sha512-2e8qq0ETcfWRI4HJBzQiA3UoyFk6tbNyG+qSaIBZLyW9Xf3sWZHN/lxe9fTh1U45DpPf07yj94KsUHHWe4Yk1A==" crossorigin="anonymous"></script>

<!--  PLUGIN JAVASCRIPT ========================================================================================================================================== -->
    <script src="../js/jquery.easing.min.js"></script>
    <script src="../js/jquery.fittext.js"></script>
    <script src="../js/wow.min.js"></script>

<!--  CUSTOM THEME JAVASCRIPT ==================================================================================================================================== -
-->
    <script src="../js/creative.js"></script>

</body>

</html>
