<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="NOODP">
    <meta name="description" content="It's going to get a little crazy on this blog! I am a new father, loving husband, and stay at home 'fommy.' Join me on my journey as I discuss hot-button topics and re-tell the mostly humourous side of being a family-mant.">
    <meta name="keywords" content="giggles, shit, giggles n shit, blog, parent, father, fommy, stay at home, funny, humour, dad, newborn, baby, nursery, web development, tech">
    <meta name="author" content="Evan Marshall">
    <link rel="icon" href="#">

    <title>Giggles N Shit Blog</title>
    
    <!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
	<script type="application/ld+json">
		[ {
		  "@context" : "http://schema.org",
		  "@type" : "Product",
		  "name" : "Giggles N Shit Blog",
		  "url" : "http://www.gigglesnshit.com/"
		}, {
		  "@context" : "http://schema.org",
		  "@type" : "Product",
		  "name" : "Giggles N Shit",
		  "image" : [ "http://www.google.com/img/portfolio/hospital.jpg", "http://www.google.com/img/portfolio/family.jpg", "http://www.google.com/img/portfolio/poo-chair.jpg", "http://www.google.com/img/portfolio/daddys-girl.jpg", "http://www.google.com/img/portfolio/football.jpg", "http://www.google.com/img/portfolio/playpin.jpg" ],
		  "description" : "It&#39;s going to get a little crazy on this blog! I am a new father, loving husband, and stay at home &#39;fommy.&#39; Join me on my journey as I discuss hot-button topics and re-tell the mostly humourous side of being a family-man.",
		  "url" : "http://www.gigglesnshit.com/"
		} ]
	</script>

<!-- MINIFIED BOOTSTRAP CSS ====================================================================================================================================== -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet" integrity="sha256-7s5uDGW3AHqw6xtJmNNtr+OBRJUlgkNJEo78P4b0yRw= sha512-nNo+yCHEyn0smMxSswnf/OnX6/KwJuZTlNZBjauKhTK0c+zT+q5JOCx0UFhXQ6rJR9jg6Es8gPuD2uZcYDLqSw==" crossorigin="anonymous">

<!-- CUSTOM FONTS ================================================================================================================================================ -->
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic" rel="stylesheet" type="text/css">
    
<!-- FONT-AWESOME ================================================================================================================================================ -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha256-3dkvEK0WLHRJ7/Csr0BZjAWxERc5WH7bdeUya2aXxdU= sha512-+L4yy6FRcDGbXJ9mPG8MT/3UCDzwR9gPeyFNMCtInsol++5m3bk2bXWKdZjvybmohrAsn3Ua5x8gfLnbE1YkOg==" crossorigin="anonymous">

<!-- PLUGIN CSS ================================================================================================================================================== -->
    <link rel="stylesheet" href="../css/animate.min.css" type="text/css">

<!-- CUSTOM CSS ================================================================================================================================================== -->
    <link rel="stylesheet" href="../css/creative.css" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body id="page-top">

    <nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">
       		<a class="navbar-brand page-scroll" href="../index.html">Giggles N Shit Blog</a>
        </div>
        <!-- /.container-fluid -->
    </nav>
    
    <aside>
        <div class="container text-center">
  			<p style="color:black;">Click <a href='../index.html' style='color:#5763AC;'>HERE</a> to be redirected to the homepage.</p>
       </div>
   </aside>
    
    <?php
	
/// VALIDATE FORM ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	
	//if form submitted with post method validator
	if ($_SERVER['REQUEST_METHOD'] == 'POST'){
		
		//processing form
		$user = $_POST['username'];
		$full_name = $_POST['name'];
		$user_email = $_POST['email'];
		$user_password = $_POST['password'];
		$confirm_password = $_POST['cpassword'];
		
		if(!empty($user) && !empty($full_name) && !empty($user_email) && !empty($user_password) && !empty($confirm_password)){
			include('connect.php');//this if statement checks to see all values of form filled out, and won't connect if not
			
			mysqli_query($dbc, "INSERT INTO userdata(username, name, email, password, cpassword) VALUES('$user', '$full_name', '$user_email', '$user_password', '$confirm_password')");/*connects to db and inserts values into table columns of table "userdata" from values stored in above variables*/
			
			//make sure everything inserts into db
			$registered = mysqli_affected_rows($dbc);
			echo '<div class="alert alert-success alert-dismissible fade in" role="alert"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">x</span></button>You have sucessfully created your account on Giggles N Shit Blog!</div>';//will return a number of rows
			
		}else{
			echo '<div class="alert alert-danger alert-dismissible fade in" role="alert"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">x</span></button>Please fill out each box in order to sign up.</div>';
		}
	}else{
		echo '<div class="alert alert-danger alert-dismissible fade in" role="alert"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">x</span></button>Internal Error, user not submitted.</div>';
	}
?>

    <section id="contact" class="bg-primary">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 text-center">
                    <h2 class="section-heading">Drop me a Line</h2>
                    <hr class="light">
                    <p>Feel free to contact me anytime, anyday via my personal email or social media accounts.</p>
                </div>
                <div class="col-lg-12 text-center">
                    <i class="fa fa-envelope-o fa-3x wow bounceIn" data-wow-delay=".1s"></i>
                    <p><a href="mailto:evanmarshall1986@gmail.com" style="color:white;">EMAIL ME!</a></p>
                </div>
                <div class="col-lg-8 col-lg-offset-2 text-center">
                    <div class="col-lg-3 text-center">
                        <a href="#" style="color:white;"><i class="fa fa-facebook fa-3x wow bounceIn" data-wow-delay=".1s"></i></a>
                    </div>
                    <div class="col-lg-3 text-center">
                        <a href="#" style="color:white;"><i class="fa fa-instagram fa-3x wow bounceIn" data-wow-delay=".1s"></i></a>
                    </div>
                    <div class="col-lg-3 text-center">
                        <a href="#" style="color:white;"><i class="fa fa-twitter fa-3x wow bounceIn" data-wow-delay=".1s"></i></a>
                    </div>
                    <div class="col-lg-3 text-center">
                        <a href="#" style="color:white;"> <i class="fa fa-pinterest fa-3x wow bounceIn" data-wow-delay=".1s"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </section>

<!-- MINIFIED BOOTSTRAP JQUERY ====================================================================================================================================--><script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>

<!--  MINIFIED BOOTSTRAP JAVASCRIPT ============================================================================================================================== --> 	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha256-KXn5puMvxCw+dAYznun+drMdG1IFl3agK0p/pqT9KAo= sha512-2e8qq0ETcfWRI4HJBzQiA3UoyFk6tbNyG+qSaIBZLyW9Xf3sWZHN/lxe9fTh1U45DpPf07yj94KsUHHWe4Yk1A==" crossorigin="anonymous"></script>

<!--  PLUGIN JAVASCRIPT ========================================================================================================================================== -->
    <script src="../js/jquery.easing.min.js"></script>
    <script src="../js/jquery.fittext.js"></script>
    <script src="../js/wow.min.js"></script>

<!--  CUSTOM THEME JAVASCRIPT ==================================================================================================================================== -->
    <script src="../js/creative.js"></script>

</body>

</html>


